name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight UTC

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow the action to push commits
      pages: write     # Allow deployment to GitHub Pages
      id-token: write  # Allow OIDC token generation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Fetch Stats.fm Music Data
        # Only fetch music data if this wasn't triggered by a GitHub Action commit
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, 'Update music data from Stats.fm') }}
        run: node scripts/fetch-music-data.js
        env:
          STATS_FM_TOKEN: ${{ secrets.STATS_FM_TOKEN }}
          
      - name: Copy music data to portfolio public folder
        # Only copy if music data was fetched
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, 'Update music data from Stats.fm') }}
        run: |
          mkdir -p portfolio/public/data/music/latest
          cp data/music/latest/*.json portfolio/public/data/music/latest/
          
      - name: Commit and push music data
        # Only fetch and commit music data if this wasn't triggered by a GitHub Action commit
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, 'Update music data from Stats.fm') }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/ portfolio/public/data/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update music data from Stats.fm [skip ci]"
            git push
          fi
          
      - name: Install dependencies
        run: npm install
        working-directory: portfolio
        
      - name: Build application
        run: npm run build
        working-directory: portfolio
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: portfolio/build
